# time.pyi — MicroPython-compatible type stubs

from typing import Any, Tuple

# Tick-related functions


def ticks_ms() -> int: ...
def ticks_us() -> int: ...
def ticks_cpu() -> int: ...
def ticks_add(ticks: int, delta: int) -> int: ...
def ticks_diff(end: int, start: int) -> int: ...

# Delay functions


def sleep(seconds: float) -> None: ...
def sleep_ms(ms: int) -> None: ...
def sleep_us(us: int) -> None: ...

# Optional: time functions for localtime/gmtime


def time() -> float: ...


def localtime(secs: float = ...) -> Tuple[int,
                                          int, int, int, int, int, int, int]: ...


def gmtime(secs: float = ...) -> Tuple[int,
                                       int, int, int, int, int, int, int]: ...
