# aioble/core.pyi — MicroPython aioble core module type stubs
# MIT license; Copyright (c) 2021 Jim Mussared

from typing import Any, Callable, Optional
import bluetooth

# Logging functions
def log_error(*args: Any) -> None: ...
def log_warn(*args: Any) -> None: ...
def log_info(*args: Any) -> None: ...

class GattError(Exception):
    _status: int
    def __init__(self, status: int) -> None: ...

def ensure_active() -> None: ...
def config(*args: Any, **kwargs: Any) -> Any: ...
def register_irq_handler(irq: Optional[Callable], shutdown: Optional[Callable]) -> None: ...
def stop() -> None: ...

# Global BLE instance
ble: bluetooth.BLE

# Logging level
log_level: int
